image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start graviton
    command: yarn dev_desktop

ports:
  - port: 6080
    onOpen: open-preview
    visibility: private
  - port: 5090
    visibility: private

vscode:
  extensions:
    - rust-lang.rust
