
image: gitpod/workspace-full-vnc

tasks:
  - name: Rust
    init: cargo build
    command: cargo run --example demo
  - name: Web
    init: npm i yarn -g && cd web && yarn
    command: yarn dev

vscode:
  extensions:
    - rust-lang.rust

ports:
  - port: 6080
    onOpen: open-preview