/* CodeMirror modes */

import '../../../node_modules/codemirror/mode/javascript/javascript.js'
import '../../../node_modules/codemirror/mode/jsx/jsx.js'
import '../../../node_modules/codemirror/mode/htmlmixed/htmlmixed.js'
import '../../../node_modules/codemirror/mode/css/css.js'
import '../../../node_modules/codemirror/mode/php/php.js'
import '../../../node_modules/codemirror/mode/d/d.js'
import '../../../node_modules/codemirror/mode/rust/rust.js'
import '../../../node_modules/codemirror/mode/ruby/ruby.js'
import '../../../node_modules/codemirror/mode/python/python.js'
import '../../../node_modules/codemirror/mode/vue/vue.js'
import '../../../node_modules/codemirror/mode/xml/xml.js'
import '../../../node_modules/codemirror/mode/htmlembedded/htmlembedded.js'
import '../../../node_modules/codemirror/mode/lua/lua.js'
import '../../../node_modules/codemirror/mode/yaml/yaml.js'
import '../../../node_modules/codemirror/mode/sql/sql.js'
import '../../../node_modules/codemirror/mode/clike/clike.js'
import '../../../node_modules/codemirror/mode/sass/sass.js'
import '../../../node_modules/codemirror/mode/php/php.js'
import '../../../node_modules/codemirror/mode/markdown/markdown.js'
import '../../../node_modules/codemirror/mode/gfm/gfm.js'
import '../../../node_modules/codemirror/mode/shell/shell.js'
import '../../../node_modules/codemirror/mode/mllike/mllike.js'
import '../../../node_modules/codemirror/mode/slim/slim.js'
import '../../../node_modules/codemirror/mode/go/go.js'
import '../../../node_modules/codemirror/mode/dart/dart.js'
