/* CodeMirror modes */

import '../../../node_modules/codemirror/mode/javascript/javascript.js'
import '../../../node_modules/codemirror/mode/jsx/jsx.js'
import '../../../node_modules/codemirror/mode/htmlmixed/htmlmixed.js'
import '../../../node_modules/codemirror/mode/css/css.js'
import '../../../node_modules/codemirror/mode/php/php.js'
import '../../../node_modules/codemirror/mode/d/d.js'
import '../../../node_modules/codemirror/mode/rust/rust.js'
import '../../../node_modules/codemirror/mode/ruby/ruby.js'
import '../../../node_modules/codemirror/mode/python/python.js'
import '../../../node_modules/codemirror/mode/vue/vue.js'
import '../../../node_modules/codemirror/mode/xml/xml.js'
import '../../../node_modules/codemirror/mode/htmlembedded/htmlembedded.js'
import '../../../node_modules/codemirror/mode/lua/lua.js'
import '../../../node_modules/codemirror/mode/yaml/yaml.js'
import '../../../node_modules/codemirror/mode/sql/sql.js'
import '../../../node_modules/codemirror/mode/clike/clike.js'
import '../../../node_modules/codemirror/mode/sass/sass.js'
import '../../../node_modules/codemirror/mode/php/php.js'
import '../../../node_modules/codemirror/mode/markdown/markdown.js'
import '../../../node_modules/codemirror/mode/gfm/gfm.js'
import '../../../node_modules/codemirror/mode/shell/shell.js'
import '../../../node_modules/codemirror/mode/mllike/mllike.js'
import '../../../node_modules/codemirror/mode/slim/slim.js'
import '../../../node_modules/codemirror/mode/go/go.js'
import '../../../node_modules/codemirror/mode/dart/dart.js'
import '../../../node_modules/codemirror/mode/brainfuck/brainfuck.js'
import '../../../node_modules/codemirror/mode/haskell/haskell.js'

/* CodeMirror addons */

import 'codemirror/addon/search/search'
import 'codemirror/addon/merge/merge'
import 'codemirror/addon/selection/active-line'
import 'codemirror/addon/edit/matchbrackets'
import 'codemirror/addon/edit/matchtags'
import 'codemirror/addon/edit/closetag'
import 'codemirror/addon/edit/closebrackets'
import 'codemirror/addon/hint/show-hint.css'
import 'codemirror/addon/hint/show-hint'
import 'codemirror/addon/hint/javascript-hint'
import 'codemirror/addon/hint/css-hint'
import 'codemirror/addon/hint/sql-hint'
import 'codemirror/addon/hint/xml-hint'
import 'codemirror/addon/hint/html-hint'
import 'codemirror/addon/hint/html-hint'
import 'codemirror/addon/fold/foldgutter'
import 'codemirror/addon/fold/foldcode'
import 'codemirror/addon/fold/foldgutter.css'
import 'codemirror/addon/fold/brace-fold'
import 'codemirror/addon/fold/indent-fold'
import 'codemirror/addon/fold/xml-fold'
import 'codemirror/addon/fold/markdown-fold'
import 'codemirror/addon/fold/comment-fold'
