const Night = {
    name:'Night',
    textTheme:'night',
    type:'theme',
    colorsScheme:{
        accentColor: "rgb(255, 0, 72)",
        textColor:'white',
        bodyBackground:'#222222',
        titlebarBackground:"#222222",
        dropmenuBackground:'#191919',
        dropmenuButtonBackground:"transparent",
        dropmenuButtonHoveringBackground:"#191919",
        dropmenuButtonText:"white",
        dropmenuButtonHoveringText:"white",
        dropmenuOptionText:"white",
        dropmenuOptionHoveringText:"white",
        controlButtonsFill:"white",
        controlButtonsHoverBackground:"rgb(60,60,60)",
        controlCloseButtonHoverBackground:"rgba(232,17,35)",
        controlCloseButtonHoverFill:"white",
        windowBackground:'#222222',
        contextmenuBackground:'#191919',
        contextmenuButtonBackground:'#191919',
        contextmenuButtonText:'white',
        contextmenuButtonHoveringBackground:'rgb(255, 0, 72);',
        contextmenuButtonHoveringText:'white',
        mainpanelBackground:'#191919',
        tabsbarBackground:'#222222',
        tabBackground:'#222222',
        tabText:'white',
        tabActiveText:'white',
        tabActiveBackground:'#191919',
        scrollbarBackground:'rgba(0,0,0,0.2)',
        scrollbarHoverBackground:'rgba(0,0,0,0.5)',
        tabIconFill:'white',
        tabIconHoverFill:'gray',
        sidemenuBackground:'#191919',
        sidemenuButtonBackground:'transparent',
        sidemenuButtonHoverBackground:'#222222',
        sidemenuButtonActiveBackground:'rgb(255, 0, 72)',
        sidemenuButtonText:'white',
        sidemenuButtonActiveText:'white',
        explorerItemText:'white',
        cardBackground:'#191919',
        buttonBackground:'#191919',
        radioBackgroundHovering:'rgb(60,60,60)',
        radioCircleBackground:'#222222',
        radioCircleBorder:'#666666',
        windowBorder:'#666666',
        fileNotSavedIndicator:'white',
        fileNotSavedIndicatorHovering:'rgb(255, 0, 72)',
        controlCloseButtonActiveBackground:'rgba(241,112,122)',
        controlCloseButtonActiveFill:'black',
        editorDialogBackground:'#191919',
        editorDialogText:'white',
        contextmenuDivider:'rgb(180,180,180)',
        statusbarBackground:'#191919',
        statusbarItemBackground:'transparent',
        statusbarItemHoveringBackground:'rgb(60,60,60)',
        statusbarItemText:'white',
        statusbarItemHoveringText:'white',
    }
}

export default Night